#include "session.hpp"
MSTL_BEGIN_NAMESPACE__
#ifdef DELETE
#undef DELETE
#endif

const HTTP_METHOD HTTP_METHOD::GET{"GET"};
const HTTP_METHOD HTTP_METHOD::POST{"POST"};
const HTTP_METHOD HTTP_METHOD::HEAD{"HEAD"};
const HTTP_METHOD HTTP_METHOD::PUT{"PUT"};
const HTTP_METHOD HTTP_METHOD::DELETE{"DELETE"};
const HTTP_METHOD HTTP_METHOD::OPTIONS{"OPTIONS"};
const HTTP_METHOD HTTP_METHOD::TRACE{"TRACE"};
const HTTP_METHOD HTTP_METHOD::CONNECT{"CONNECT"};

MSTL_END_NAMESPACE__
